# Generated by Django 4.1.7 on 2023-03-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0007_chirakkal_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHIRAKKAL_DATA',
        ),
        migrations.DeleteModel(
            name='PANCHAYAT_BOUNDARY',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
