# Generated by Django 4.1.7 on 2023-03-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0015_drainage_l_delete_chirakkal_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DRAINAGE_L',
        ),
        migrations.AddField(
            model_name='upload',
            name='db_host',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='db_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='db_pass',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='db_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
