# Generated by Django 4.1.7 on 2023-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0016_delete_drainage_l_upload_db_host_upload_db_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, max_length=250, null=True)),
                ('db_user', models.CharField(blank=True, max_length=250, null=True)),
                ('db_pass', models.CharField(blank=True, max_length=250, null=True)),
                ('db_host', models.CharField(blank=True, max_length=250, null=True)),
                ('db_port', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='db_pass',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='db_user',
        ),
    ]
