# Generated by Django 4.1.7 on 2023-03-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0021_panchayat_boundary_delete_road'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PANCHAYAT_BOUNDARY',
        ),
    ]
