# Generated by Django 4.1.7 on 2023-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0023_chirakkal_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHIRAKKAL_DATA',
        ),
    ]
