# Generated by Django 4.1.7 on 2023-03-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0025_panchayat_boundary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PANCHAYAT_BOUNDARY',
        ),
    ]
