# Generated by Django 4.1.7 on 2023-03-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0048_chirakkal_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHIRAKKAL_DATA',
        ),
        migrations.DeleteModel(
            name='DRAINAGE_L',
        ),
        migrations.DeleteModel(
            name='FINAL_ROAD_CHIRAKKAL',
        ),
        migrations.DeleteModel(
            name='PANCHAYAT_BOUNDARY',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
