# Generated by Django 4.1.7 on 2023-03-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapedata', '0051_road'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DRAINAGE_L',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
